article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/' ,views.dashboard, name = "dashboard"),
    path('addarticle/', views.addarticle, name = "addarticle"),
    path('article/<int:id>/', views.detail, name= "detail"),
    path('update/<int:id>/', views.update, name= "update"),
    path('delete/<int:id>/', views.delete, name= "delete"),
    path('', views.articles, name= "articles"),
    path('comment/<int:id>/', views.addComment, name= "comment"),
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include
from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('money', views.money, name= "money"),
    path('about/', views.about, name = "about"),
    path('articles/', include("article.urls")),
    path('user/', include("user.urls")),
    
]

# Media ucun lazimdi
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.loginUser, name = "login"),
    path('logout/', views.logoutUser, name = "logout"),
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.core.validators import MinLengthValidator

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE, verbose_name = "Yazar")
    title = models.CharField(max_length=50, verbose_name = "Bashliq", validators=[MinLengthValidator(10)])
    content = RichTextField()
    article_image = models.FileField(blank=True, null=True, verbose_name= "Meqaleye shekil elave edin")
    created_date = models.DateTimeField(auto_now_add=True, verbose_name= "Yarandigi tarix")
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete = models.CASCADE, verbose_name = "Meqale", related_name = "comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "Ad")
    comment_content = models.CharField(max_length = 200, verbose_name = "Sherh")
    comment_date = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "article_image"]


STATES = (
    ('', 'Choose...'),
    ('MG', 'Minas Gerais'),
    ('SP', 'Sao Paulo'),
    ('RJ', 'Rio de Janeiro')
)

class AddressForm(forms.Form):
    email = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    password = forms.CharField(widget=forms.PasswordInput())
    address_1 = forms.CharField(
        label='Address',
        widget=forms.TextInput(attrs={'placeholder': '1234 Main St'})
    )
    address_2 = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': 'Apartment, studio, or floor'})
    )
    city = forms.CharField()
    state = forms.ChoiceField(choices=STATES)
    zip_code = forms.CharField(label='Zip')
    check_me_out = forms.BooleanField(required=False)

article/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404, reverse
from .forms import ArticleForm, AddressForm
from django.contrib import messages
from .models import Article, Comment
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, "index.html")

def money(request):
    form = AddressForm(request.POST or None)
    if form.is_valid():
        email = form.cleaned_data.get("email")
        address = form.cleaned_data.get("city")
        messages.success(request,"{} li istifadeci burada yashayir {}".format(email, address))
        return redirect("index")
    return render(request, "money.html", {"form":form})

def articles(request):
    keyword = request.GET.get("keyword")
    choosenuser = request.GET.get("choosenuser")
    
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        if articles:
            return render(request, "articles.html", {"articles":articles})
        else:
            articles = Article.objects.filter(content__contains = keyword)
            return render(request, "articles.html", {"articles":articles}) 

    if choosenuser:
        articles = Article.objects.filter(author__contains = choosenuser)
        if articles:
            return render(request, "articles.html", {"articles":articles})            

    articles = Article.objects.all()
    return render(request, "articles.html", {"articles":articles})


def about(request):
    return render(request, "about.html")

@login_required(login_url = "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    return render(request, "dashboard.html", {"articles":articles})

@login_required(login_url = "user:login")
def addarticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save() 
        messages.success(request, "Meqale elave olundu")
        return redirect("index")
    return render(request, "addarticle.html", {"form":form})

def detail(request, id):
    #article = Article.objects.filter(id = id).first()
    article = get_object_or_404(Article, id=id)
    comments = article.comments.all()
    
    return render(request, "detail.html", {"article":article, "comments":comments})

@login_required
def addComment(request,id):
    article = get_object_or_404(Article, id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()
    return redirect(reverse("article:detail",kwargs={"id":id}))


@login_required(login_url = "user:login")
def update(request, id):
    article = get_object_or_404(Article, id=id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance = article)
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        messages.success(request, "Meqale yenilendi")
        return redirect("article:dashboard")
    return render(request, "update.html", {"form":form})

@login_required(login_url = "user:login")
def delete(request, id):
    article = get_object_or_404(Article, id=id)
    article.delete()
    messages.success(request, "Meqale sikdirdi")
    return redirect("article:dashboard")

article/templates/about.html
{% extends "layout.html" %}

{% block body %}
<h3>Haqqimizda</h3>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Fluid jumbotron</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Fusce ut placerat orci nulla pellentesque dignissim enim. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. Dui nunc mattis enim ut tellus elementum sagittis vitae et. Justo donec enim diam vulputate ut pharetra sit amet. Non odio euismod lacinia at quis risus sed vulputate odio. Molestie at elementum eu facilisis sed odio. Viverra suspendisse potenti nullam ac. Amet venenatis urna cursus eget nunc scelerisque. Iaculis eu non diam phasellus vestibulum lorem sed. Praesent elementum facilisis leo vel fringilla est ullamcorper eget. Eget nullam non nisi est sit.

Id volutpat lacus laoreet non curabitur gravida arcu. A diam maecenas sed enim ut sem viverra. Id diam maecenas ultricies mi eget mauris. Malesuada fames ac turpis egestas sed. Quis lectus nulla at volutpat diam. Morbi non arcu risus quis varius quam quisque id. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Neque ornare aenean euismod elementum nisi quis eleifend. Sit amet tellus cras adipiscing enim eu turpis egestas pretium. Nunc pulvinar sapien et ligula ullamcorper malesuada proin libero nunc. Adipiscing diam donec adipiscing tristique risus nec feugiat. Neque egestas congue quisque egestas diam in arcu. Tellus elementum sagittis vitae et leo duis ut diam. Ornare suspendisse sed nisi lacus sed viverra tellus in. Quis enim lobortis scelerisque fermentum dui faucibus in ornare. Risus viverra adipiscing at in.</p>
  </div>
</div>

{% endblock body %}

article/templates/addarticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Meqale yukle</h3>
    <hr>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>
        <button type="submit" class = "btn btn-primary">Meqale yukle</button>
    </form>
  </div>
</div>

{% endblock body %}

article/templates/articles.html
{% extends "layout.html" %}
{% load static %}
{% block css_place %}
<link rel="stylesheet" href="{% static 'css/style_tables.css' %}">
{% endblock  %}
{% block body %}
<div class="container-fluid">
<div class="row">
    <div class="col-8">
    <h1 class="my-4">Məqalələr</h1>
    </div>
    <div class="col-sm" style="margin-top:30px;">
    <form class="form-inline md-form ml-auto mb-4">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="text" name = "keyword" placeholder="Axtar" aria-label="Search">
        <button class="btn btn-primary btn-rounded btn-sm my-0" type="submit">Axtar</button>
    </form>
    </div>
</div>   
</div>

<hr>
{% if articles %}
{% for article in articles %}

<div class="card mb-4">
    {% if article.article_image %}
        <a href="{% url 'article:detail' article.id %}">
        <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
        </a>
    {% else %}
        <a href="{% url 'article:detail' article.id %}">
        <img class="card-img-top" src="../media/beachr.jpg" alt="Card image cap">
        </a>
    {% endif %}   
    <div class="card-body">
        <h2 class="card-title">{{article.title}}</h2>
    <p class="card-text">{{article.content|safe|truncatewords:20}}</p>
    <a href="{% url 'article:detail' article.id %}" class="btn btn-primary">Daha çox oxu →</a>
    </div>
    <div class="card-footer text-muted">
    Paylaşıldı {{article.created_date}}
    <form>
    {% csrf_token %}
    {{ form }}
    <input type="hidden" name="choosenuser" value="{{article.author}}">
    <input type="submit" class="submit_btn btn label-success" value="{{article.author}}" />
    </form>
    </div>
</div>
    <hr>
{% endfor %}


{% else %}
<div class = "alert alert-danger">
Gosterilecek meqale yoxdur seni shansli ogul.
</div>
{% endif %}
{% endblock  %}

article/templates/articles2.html
{% extends "layout.html" %}
{% load static %}
{% block css_place %}
<link rel="stylesheet" href="{% static 'css/style_tables.css' %}">
{% endblock  %}
{% block body %}
<div class="container-fluid">
<div class="row">
    <div class="col-8">
    <h1 class="my-4">Məqalələr</h1>
    </div>
    <div class="col-sm" style="margin-top:30px;">
    <form class="form-inline md-form ml-auto mb-4">
        {% csrf_token %}
        <input class="form-control mr-sm-2" type="text" name = "keyword" placeholder="Axtar" aria-label="Search">
        <button class="btn btn-primary btn-rounded btn-sm my-0" type="submit">Axtar</button>
    </form>
    </div>
</div>   
</div>

<hr>
{% if articles %}
{% for article in articles %}

<div class="card mb-4">
    {% if article.article_image %}
        <a href="{% url 'article:detail' article.id %}">
        <img class="card-img-top" src="{{article.article_image.url}}" alt="Card image cap">
        </a>
    {% else %}
        <a href="{% url 'article:detail' article.id %}">
        <img class="card-img-top" src="../media/beachr.jpg" alt="Card image cap">
        </a>
    {% endif %}   
    <div class="card-body">
        <h2 class="card-title">{{article.title}}</h2>
    <p class="card-text">{{article.content|safe|truncatewords:20}}</p>
    <a href="#" class="btn btn-primary">Daha çox oxu →</a>
    </div>
    <div class="card-footer text-muted">
    Paylaşıldı {{article.created_date}}
    <a href="#">{{article.author}}</a>
    </div>
</div>
    <hr>
{% endfor %}


{% else %}
<div class = "alert alert-danger">
Gosterilecek meqale yoxdur seni shansli ogul.
</div>
{% endif %}
{% endblock  %}

article/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

article/templates/dashboard.html
{% extends "layout.html" %}
{% load static %}
{% block css_place %}
<link rel="stylesheet" href="{% static 'css/style_tables.css' %}">
{% endblock  %}
{% block body %}
<h1 class="display-4">Meqalelerim</h1>
<hr>
<p>
Xoshgeldin aq <small>{{request.user.username}}</small>
</p>
<br>

{% if articles %}
<table class="table table-hover">
<caption>Meqalelerinin siyahisi</caption>
  <thead>
    <tr class="bg-primary" align="center">
      <th scope="col">id</th>
      <th scope="col">Bashliq</th>
      <th scope="col">Tarix</th>
      <th scope="col">Duzelish et</th>
      <th scope="col">Sil</th>
    </tr>
  </thead>
  <tbody>
  {% for article in articles %}
    <tr  align="center">
      <td>{{article.id}}</th>
      <td><a href="/articles/article/{{article.id}}">{{article.title}}<a/></td>
      <td><a href="/articles/article/{{article.id}}">{{article.created_date}}</a></td>
      <td><a class="btn btn-primary btn-sm" href="/articles/update/{{article.id}}">Duzelish et</a></td>
      <td><a class="btn btn-danger btn-sm" href="/articles/delete/{{article.id}}">Sil</a></td>
    </tr>
  {% endfor %}
  </tbody>
</table>
<br>
<p align="right">
<a class = "btn btn-primary" href = "/articles/addarticle">Meqale elave et</a>
</p>
{% else %}
<div class="alert alert-danger" align="center">
Hazirda gosterilecek meqaleniz yoxdur.
</div>
{% endif %}
{% endblock body %}

article/templates/detail.html
{% extends "layout.html" %}
{% block body %}
<div class="row">

      <!-- Post Content Column -->
      <div class="col-lg-8">

        <!-- Title -->
        <h3 class="mt-4">{{article.title}}</h3>
        <!-- Author -->
        <div class="row no-gutters">
        <div class="col-12 col-sm-6 col-md-8">
        <p class="lead" stye="text-align:justify;">
          by
          <a href="#">{{article.author}}</a>
        </p>
        </div>
        <div class="col-6 col-md-4">
        {% if request.user == article.author %}
          <p class="lead" stye="text-align:justify;">
          <a href="{% url 'article:update' article.id %}">Meqalede duzelish et</a>
        {% endif %}
        </p>
        </div>
        </div>
        <div>

        <!-- Date/Time -->
        <p>{{article.created_date}}</p>

        <hr>

        <!-- Preview Image -->
        {% if article.article_image %}
        <img class="img-fluid rounded" src="{{article.article_image.url}}" alt="">
        {% endif %}
        <hr>
        <!-- Post Content -->
        <p class="lead">
            {{article.content|safe}}
        </p>
        <hr>
        
        {% if user.is_authenticated %}
                    <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">Sherh yaz:</h5>
          <div class="card-body">
            <form method="post" action="{% url 'article:comment' article.id %}">
            {% csrf_token %}
              <div class="form-group">
                <label for="formGroupExampleInput">Adiniz</label>
                <input name = "comment_author" class="form-control" rows="1" placeholder="{{request.user}}">
              </div>
              <div class="form-group">
                <label for="formGroupExampleInput">Sherh</label>
                <textarea name = "comment_content" class="form-control" rows="3"></textarea>
              </div>
              <button type="submit" class="btn btn-primary">Paylash</button>
            </form>
          </div>
        </div>
        {% if comments %}
        <!-- Single Comment -->
        <div class="card my-4">
        <h5 class="card-header">Sherhler</h5>
        <br>
        {% for comment in comments %}
          <div class="media mb-4" style="padding:10px;">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
              <div class="media-body">
                <h5 class="mt-0">{{comment.comment_author}}</h5>
                <small>{{comment.comment_date}}</small><br>
                {{comment.comment_content}}
              </div>
          </div>
        <hr>   
        {% endfor %}
        </div>
        {% else %}
        <div class = "alert alert-info">
        Helem ki sherh yoxdur
        </div>
        {% endif %}
      </div>
    </div>
        {% else %}
        <div class="alert alert-info" role="alert">
        Sherhleri gore bilmek ucun <a href="{% url 'user:login' %}" class="alert-link">bura tappildadaraq daxil olmalisan</a>. Tabbiltam bura.
        </div>
        {% endif %}


    <!-- /.row -->

{% endblock  %}

article/templates/index.html
{% extends "layout.html" %}
{% block body %}

<div class="jumbotron">
  <h1 class="display-4">Hello, {{request.user.username}}!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
  </p>
</div>

<p>
  {% if request.user.is_authenticated %}
    Ufff ne bomba cividi bu,{{request.user.username}}
  {% else %}
    Burda civi zad yoxdu
  {% endif %}
</p>



{% endblock body %}

article/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    {% block css_place %}{% endblock  %}
    <title>Blog</title>
</head>
<body>
</nav>
    
    {% include "includes/navbar.html" %}

        <div style = "margin-top: 100px; margin-bottom: 100px;" class = "container">
            {% if messages %}
            {% for message in messages %}
                {% if message.tags == "info" %}
                    <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}
            {% endfor %}
            {% endif %}
            {% block body %}
            {% endblock body %}
        </div>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

article/templates/login.html
{% extends "layout.html" %}
{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Daxil ol</h3>
    <hr>
    <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <div class="row">
        <div class="col-8">
        <button type="submit" class = "btn btn-primary">Daxil ol</button>
        </div>
        <div class="col-4">
        <p style="text-align:center">
        <a href="{% url 'user:register' %}">Qeydiyyatdan kec</a>
        </p>
        </div>
        </div>
    </form>
  </div>
</div>

{% endblock body %}

article/templates/money.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    
<form method="post">
    {% csrf_token %}
    <table>{{ form|crispy }}</table>
    <button type="submit">Sign in</button>
  </form>

{% endblock  %}

article/templates/register.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Qeydiyyatdan kec</h3>
    <hr>
    <form method = "post">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <button type="submit" class = "btn btn-primary">Qeydiyyati tamamla</button>
    </form>
  </div>
</div>

{% endblock body %}

article/templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
  <div class="col-md-6 offset-md-3">
    <h3>Meqale yenile</h3>
    <hr>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <br>
        <button type="submit" class = "btn btn-primary">Meqale yenile</button>
    </form>
  </div>
</div>

{% endblock body %}